export const endpoints = {
  auth: {
    login: "/auth/login",
    me: "/auth/me",
    updateMe: "/auth/me",
  },
  admin: {
    cooperatives: "/admin/cooperatives",
    managers: "/admin/managers",
    users: "/admin/users",
    disableUser: (userId: string) => `/admin/users/${userId}/disable`,
    enableUser: (userId: string) => `/admin/users/${userId}/enable`,
    deleteUser: (userId: string) => `/admin/users/${userId}`,
  },
  superAdmin: {
    institutions: "/super-admin/institutions",
    institution: (id: string) => `/super-admin/institutions/${id}`,
    deactivateInstitution: (id: string) => `/super-admin/institutions/${id}/deactivate`,
    cooperatives: "/super-admin/cooperatives",
    cooperative: (id: string) => `/super-admin/cooperatives/${id}`,
    deactivateCooperative: (id: string) => `/super-admin/cooperatives/${id}/deactivate`,
    assignInstitution: (id: string) => `/super-admin/cooperatives/${id}/assign-institution`,
    makeIndependent: (id: string) => `/super-admin/cooperatives/${id}/make-independent`,
    cooperativeUsers: (id: string) => `/super-admin/cooperatives/${id}/users`,
    enableUser: (id: string) => `/super-admin/users/${id}/enable`,
    disableUser: (id: string) => `/super-admin/users/${id}/disable`,
    institutionAdmins: (institutionId: string) => `/super-admin/institutions/${institutionId}/admins`,
    enableInstitutionAdmin: (userId: string) => `/super-admin/institution-admins/${userId}/enable`,
    disableInstitutionAdmin: (userId: string) => `/super-admin/institution-admins/${userId}/disable`,
    hierarchy: "/super-admin/hierarchy",
    oversightCooperatives: "/super-admin/oversight/cooperatives",
    insightsCooperativeMembers: (id: string) => `/super-admin/insights/cooperatives/${id}/members`,
  },
  institutionAdmin: {
    institution: "/institution-admin/institution",
    cooperatives: "/institution-admin/cooperatives",
    cooperative: (id: string) => `/institution-admin/cooperatives/${id}`,
    cooperativeUsers: (id: string) => `/institution-admin/cooperatives/${id}/users`,
    enableUser: (id: string) => `/institution-admin/users/${id}/enable`,
    disableUser: (id: string) => `/institution-admin/users/${id}/disable`,
    oversightCooperatives: "/institution-admin/oversight/cooperatives",
    insightsCooperativeMembers: (id: string) => `/institution-admin/insights/cooperatives/${id}/members`,
  },
  members: {
    list: "/members",
    detail: (id: string) => `/members/${id}`,
    update: (id: string) => `/members/${id}`,
    delete: (id: string) => `/members/${id}`,
    contact: (id: string) => `/members/${id}/contact`,
  },
  farmers: {
    list: "/farmers",
    detail: (id: string) => `/farmers/${id}`,
    parcels: (id: string) => `/parcels?farmer_id=${id}`,
    charges: (id: string) => `/farmers/${id}/global-charges`,
  },
  parcels: {
    list: "/parcels",
    detail: (id: string) => `/parcels/${id}`,
    update: (id: string) => `/parcels/${id}`,
    delete: (id: string) => `/parcels/${id}`,
    preHarvest: (id: string) => `/parcels/${id}/pre-harvest`,
    preHarvestInit: (id: string) => `/parcels/${id}/pre-harvest/init`,
  },
  preHarvestEvents: {
    update: (id: string, parcelId: string) => `/pre-harvest-events/${id}?parcel_id=${parcelId}`,
    complete: (id: string, parcelId: string) => `/pre-harvest-events/${id}/complete?parcel_id=${parcelId}`,
  },
  charges: {
    list: "/charges",
    detail: (id: string) => `/charges/${id}`,
    update: (id: string) => `/charges/${id}`,
    delete: (id: string) => `/charges/${id}`,
  },
  fields: {
    list: "/fields",
    detail: (id: string) => `/fields/${id}`,
    update: (id: string) => `/fields/${id}`,
    delete: (id: string) => `/fields/${id}`,
  },
  products: {
    list: "/products",
    detail: (id: string) => `/products/${id}`,
    update: (id: string) => `/products/${id}`,
    delete: (id: string) => `/products/${id}`,
  },
  inputs: {
    list: "/inputs",
    detail: (id: string) => `/inputs/${id}`,
    update: (id: string) => `/inputs/${id}`,
    delete: (id: string) => `/inputs/${id}`,
    justificatif: (id: string) => `/inputs/${id}/justificatif`,
  },
  farmerAdvances: {
    summary: "/farmer-advances/summary",
    byFarmer: (farmerId: string) => `/farmer-advances/farmer/${farmerId}`,
    list: "/farmer-advances",
    update: (id: string) => `/farmer-advances/${id}`,
    devis: (id: string) => `/farmer-advances/${id}/devis`,
    cancel: (id: string) => `/farmer-advances/${id}/cancel`,
  },
  treasury: {
    list: "/treasury",
    stats: "/treasury/stats",
    update: (id: string) => `/treasury/${id}`,
    justificatif: (id: string) => `/treasury/${id}/justificatif`,
    cancel: (id: string) => `/treasury/${id}/cancel`,
  },
  stocks: {
    list: "/stocks",
    detail: (id: string) => `/stocks/${id}`,
    update: (id: string) => `/stocks/${id}`,
    increase: (id: string) => `/stocks/${id}/increase`,
    decrease: (id: string) => `/stocks/${id}/decrease`,
    delete: (id: string) => `/stocks/${id}`,
  },
  stockMovements: {
    list: "/stock-movements",
    detail: (id: string) => `/stock-movements/${id}`,
  },
  batches: {
    list: "/batches",
    previewReference: (productId: string) => `/batches/reference-preview?product_id=${productId}`,
    detail: (id: string) => `/batches/${id}`,
    update: (id: string) => `/batches/${id}`,
    updateStatus: (id: string) => `/batches/${id}/status`,
    approveCharge: (id: string) => `/batches/${id}/approve-charge`,
    activatePreHarvest: (id: string) => `/batches/${id}/activate-preharvest`,
    stopPreHarvest: (id: string) => `/batches/${id}/stop-preharvest`,
    updatePreHarvestStepStatuses: (id: string) => `/batches/${id}/preharvest-step-statuses`,
    completePreHarvest: (id: string) => `/batches/${id}/complete-preharvest`,
    delete: (id: string) => `/batches/${id}`,
  },
  processSteps: {
    list: "/process-steps",
    detail: (id: string) => `/process-steps/${id}`,
    update: (id: string) => `/process-steps/${id}`,
    complete: (id: string) => `/process-steps/${id}/complete`,
    delete: (id: string) => `/process-steps/${id}`,
  },
  analytics: {
    dashboard: "/analytics/dashboard",
    batchMetrics: (id: string) => `/analytics/batches/${id}/metrics`,
    batchAnomaly: (id: string) => `/analytics/batches/${id}/anomaly`,
    batchRecommendation: (id: string) => `/analytics/batches/${id}/recommendation`,
    preHarvestSummary: "/analytics/pre-harvest/summary",
    preHarvestCostsByFarmer: "/analytics/pre-harvest/costs-by-farmer",
    preHarvestCostsByParcel: "/analytics/pre-harvest/costs-by-parcel",
    preHarvestCostsByCrop: "/analytics/pre-harvest/costs-by-crop",
    preHarvestCostsByHectare: "/analytics/pre-harvest/costs-by-hectare",
  },
  chat: {
    ask: "/chat",
    agentAsk: "/chat/agent",
    sessions: "/chat/sessions",
    session: (sessionId: string) => `/chat/sessions/${sessionId}`,
    messages: (sessionId: string) => `/chat/sessions/${sessionId}/messages`,
  },
  commercial: {
    catalog: "/commercial/catalog",
    catalogDelete: (id: string) => `/commercial/catalog/${id}`,
    catalogStatus: (id: string, status: "active" | "hidden") => `/commercial/catalog/${id}/status?status=${status}`,
    orders: "/commercial/orders",
    orderStatus: (id: string) => `/commercial/orders/${id}/status`,
    orderStats: "/commercial/orders/stats",
    invoices: "/commercial/invoices",
    invoiceStats: "/commercial/invoices/stats",
    invoiceDetail: (id: string) => `/commercial/invoices/${id}`,
  },
  reference: {
    metrics: "/reference/metrics",
    knowledge: "/reference/knowledge",
  },
};
