export const endpoints = {
  auth: {
    login: "/auth/login",
    me: "/auth/me",
    updateMe: "/auth/me",
  },
  admin: {
    cooperatives: "/admin/cooperatives",
    managers: "/admin/managers",
    users: "/admin/users",
    disableUser: (userId: string) => `/admin/users/${userId}/disable`,
    enableUser: (userId: string) => `/admin/users/${userId}/enable`,
    deleteUser: (userId: string) => `/admin/users/${userId}`,
  },
  members: {
    list: "/members",
    detail: (id: string) => `/members/${id}`,
    update: (id: string) => `/members/${id}`,
    delete: (id: string) => `/members/${id}`,
    contact: (id: string) => `/members/${id}/contact`,
  },
  farmers: {
    list: "/farmers",
    detail: (id: string) => `/farmers/${id}`,
    parcels: (id: string) => `/parcels?farmer_id=${id}`,
    charges: (id: string) => `/farmers/${id}/global-charges`,
  },
  parcels: {
    list: "/parcels",
    detail: (id: string) => `/parcels/${id}`,
    update: (id: string) => `/parcels/${id}`,
    delete: (id: string) => `/parcels/${id}`,
    preHarvest: (id: string) => `/parcels/${id}/pre-harvest`,
    preHarvestInit: (id: string) => `/parcels/${id}/pre-harvest/init`,
  },
  preHarvestEvents: {
    update: (id: string, parcelId: string) => `/pre-harvest-events/${id}?parcel_id=${parcelId}`,
    complete: (id: string, parcelId: string) => `/pre-harvest-events/${id}/complete?parcel_id=${parcelId}`,
  },
  charges: {
    list: "/charges",
    detail: (id: string) => `/charges/${id}`,
    update: (id: string) => `/charges/${id}`,
    delete: (id: string) => `/charges/${id}`,
  },
  fields: {
    list: "/fields",
    detail: (id: string) => `/fields/${id}`,
    update: (id: string) => `/fields/${id}`,
    delete: (id: string) => `/fields/${id}`,
  },
  products: {
    list: "/products",
    detail: (id: string) => `/products/${id}`,
    update: (id: string) => `/products/${id}`,
    delete: (id: string) => `/products/${id}`,
  },
  inputs: {
    list: "/inputs",
    detail: (id: string) => `/inputs/${id}`,
    update: (id: string) => `/inputs/${id}`,
    delete: (id: string) => `/inputs/${id}`,
  },
  farmerAdvances: {
    summary: "/farmer-advances/summary",
    byFarmer: (farmerId: string) => `/farmer-advances/farmer/${farmerId}`,
    list: "/farmer-advances",
    update: (id: string) => `/farmer-advances/${id}`,
    cancel: (id: string) => `/farmer-advances/${id}/cancel`,
  },
  treasury: {
    list: "/treasury",
    stats: "/treasury/stats",
    update: (id: string) => `/treasury/${id}`,
    cancel: (id: string) => `/treasury/${id}/cancel`,
  },
  stocks: {
    list: "/stocks",
    detail: (id: string) => `/stocks/${id}`,
    update: (id: string) => `/stocks/${id}`,
    increase: (id: string) => `/stocks/${id}/increase`,
    decrease: (id: string) => `/stocks/${id}/decrease`,
    delete: (id: string) => `/stocks/${id}`,
  },
  batches: {
    list: "/batches",
    previewReference: (productId: string) => `/batches/reference-preview?product_id=${productId}`,
    detail: (id: string) => `/batches/${id}`,
    update: (id: string) => `/batches/${id}`,
    updateStatus: (id: string) => `/batches/${id}/status`,
    delete: (id: string) => `/batches/${id}`,
  },
  processSteps: {
    list: "/process-steps",
    detail: (id: string) => `/process-steps/${id}`,
    update: (id: string) => `/process-steps/${id}`,
    complete: (id: string) => `/process-steps/${id}/complete`,
    delete: (id: string) => `/process-steps/${id}`,
  },
  analytics: {
    dashboard: "/analytics/dashboard",
    batchMetrics: (id: string) => `/analytics/batches/${id}/metrics`,
    batchAnomaly: (id: string) => `/analytics/batches/${id}/anomaly`,
    batchRecommendation: (id: string) => `/analytics/batches/${id}/recommendation`,
    preHarvestSummary: "/analytics/pre-harvest/summary",
    preHarvestCostsByFarmer: "/analytics/pre-harvest/costs-by-farmer",
    preHarvestCostsByParcel: "/analytics/pre-harvest/costs-by-parcel",
    preHarvestCostsByCrop: "/analytics/pre-harvest/costs-by-crop",
    preHarvestCostsByHectare: "/analytics/pre-harvest/costs-by-hectare",
  },
  chat: {
    ask: "/chat",
    sessions: "/chat/sessions",
    session: (sessionId: string) => `/chat/sessions/${sessionId}`,
    messages: (sessionId: string) => `/chat/sessions/${sessionId}/messages`,
  },
  commercial: {
    catalog: "/commercial/catalog",
    catalogDelete: (id: string) => `/commercial/catalog/${id}`,
    catalogStatus: (id: string, status: "active" | "hidden") => `/commercial/catalog/${id}/status?status=${status}`,
    orders: "/commercial/orders",
    orderStatus: (id: string) => `/commercial/orders/${id}/status`,
    orderStats: "/commercial/orders/stats",
    invoices: "/commercial/invoices",
    invoiceStats: "/commercial/invoices/stats",
    invoiceDetail: (id: string) => `/commercial/invoices/${id}`,
  },
  reference: {
    metrics: "/reference/metrics",
    knowledge: "/reference/knowledge",
  },
};
