"""add ml tables

Revision ID: 578e8a300e78
Revises: ba235d013f9c
Create Date: 2026-04-15 16:40:22.477793
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '578e8a300e78'
down_revision: Union[str, None] = 'ba235d013f9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ml_prediction_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('model_version', sa.String(length=80), nullable=False),
    sa.Column('product', sa.String(length=120), nullable=True),
    sa.Column('critical_stage', sa.String(length=120), nullable=True),
    sa.Column('predicted_loss_pct', sa.Float(), nullable=True),
    sa.Column('expected_efficiency_pct', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False), nullable=True),
    sa.Column('anomaly_score', sa.Float(), nullable=True),
    sa.Column('is_anomalous', sa.Boolean(), nullable=True),
    sa.Column('input_snapshot', sa.JSON(), nullable=False),
    sa.Column('output_snapshot', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_prediction_logs'))
    )
    op.create_index(op.f('ix_ml_prediction_logs_batch_id'), 'ml_prediction_logs', ['batch_id'], unique=False)
    op.create_table('ml_recommendation_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('structured_recommendation', sa.JSON(), nullable=False),
    sa.Column('llm_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_recommendation_logs'))
    )
    op.create_index(op.f('ix_ml_recommendation_logs_batch_id'), 'ml_recommendation_logs', ['batch_id'], unique=False)
    op.create_table('ml_training_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dataset_rows', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_training_runs'))
    )
    op.create_table('ml_model_registry',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=80), nullable=False),
    sa.Column('version', sa.String(length=80), nullable=False),
    sa.Column('artifact_path', sa.Text(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('training_run_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['training_run_id'], ['ml_training_runs.id'], name=op.f('fk_ml_model_registry_training_run_id_ml_training_runs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ml_model_registry'))
    )
    op.create_table('recommendation_feedback_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recommendation_log_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recommendation_log_id'], ['ml_recommendation_logs.id'], name=op.f('fk_recommendation_feedback_logs_recommendation_log_id_ml_recommendation_logs'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendation_feedback_logs'))
    )
    op.create_index(op.f('ix_recommendation_feedback_logs_recommendation_log_id'), 'recommendation_feedback_logs', ['recommendation_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendation_feedback_logs_recommendation_log_id'), table_name='recommendation_feedback_logs')
    op.drop_table('recommendation_feedback_logs')
    op.drop_table('ml_model_registry')
    op.drop_table('ml_training_runs')
    op.drop_index(op.f('ix_ml_recommendation_logs_batch_id'), table_name='ml_recommendation_logs')
    op.drop_table('ml_recommendation_logs')
    op.drop_index(op.f('ix_ml_prediction_logs_batch_id'), table_name='ml_prediction_logs')
    op.drop_table('ml_prediction_logs')
    # ### end Alembic commands ###
