"""initial schema

Revision ID: ba235d013f9c
Revises: 
Create Date: 2026-04-15 12:35:18.033849
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = 'ba235d013f9c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cooperatives',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('region', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ONBOARDING', 'SUSPENDED', name='cooperativestatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cooperatives'))
    )
    op.create_index(op.f('ix_cooperatives_name'), 'cooperatives', ['name'], unique=True)
    op.create_table('members',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SEASONAL', name='memberstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_members_cooperative_id_cooperatives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_members')),
    sa.UniqueConstraint('cooperative_id', 'code', name='uq_members_cooperative_code')
    )
    op.create_index(op.f('ix_members_cooperative_id'), 'members', ['cooperative_id'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('quality_grade', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_products_cooperative_id_cooperatives'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index(op.f('ix_products_cooperative_id'), 'products', ['cooperative_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.String(length=160), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', name='userrole', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus', native_enum=False), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_users_cooperative_id_cooperatives'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_cooperative_id'), 'users', ['cooperative_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('batches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('creation_date', sa.Date(), nullable=False),
    sa.Column('initial_qty', sa.Float(), nullable=False),
    sa.Column('current_qty', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'IN_PROGRESS', 'COMPLETED', 'ARCHIVED', name='batchstatus', native_enum=False), nullable=False),
    sa.Column('created_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_batches_cooperative_id_cooperatives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], name=op.f('fk_batches_created_by_user_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_batches_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_batches'))
    )
    op.create_index(op.f('ix_batches_code'), 'batches', ['code'], unique=True)
    op.create_index(op.f('ix_batches_cooperative_id'), 'batches', ['cooperative_id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('area', sa.Float(), nullable=False),
    sa.Column('soil_type', sa.String(length=120), nullable=True),
    sa.Column('irrigation_type', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_fields_cooperative_id_cooperatives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_fields_member_id_members'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fields'))
    )
    op.create_index(op.f('ix_fields_cooperative_id'), 'fields', ['cooperative_id'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_stocks_cooperative_id_cooperatives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_stocks_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stocks')),
    sa.UniqueConstraint('cooperative_id', 'product_id', name='uq_stocks_cooperative_product')
    )
    op.create_index(op.f('ix_stocks_cooperative_id'), 'stocks', ['cooperative_id'], unique=False)
    op.create_table('inputs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('grade', sa.String(length=40), nullable=False),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'QUALITY_CONTROL', 'VALIDATED', name='inputstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperatives.id'], name=op.f('fk_inputs_cooperative_id_cooperatives'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], name=op.f('fk_inputs_field_id_fields'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_inputs_member_id_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_inputs_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inputs'))
    )
    op.create_index(op.f('ix_inputs_cooperative_id'), 'inputs', ['cooperative_id'], unique=False)
    op.create_table('process_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.String(length=80), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('qty_in', sa.Float(), nullable=False),
    sa.Column('qty_out', sa.Float(), nullable=False),
    sa.Column('waste_qty', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FLAGGED', name='processstepstatus', native_enum=False), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_process_steps_batch_id_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_process_steps'))
    )
    op.create_index(op.f('ix_process_steps_batch_id'), 'process_steps', ['batch_id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('loss_pct', sa.Float(), nullable=False),
    sa.Column('efficiency_pct', sa.Float(), nullable=False),
    sa.Column('anomaly_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel', native_enum=False), nullable=False),
    sa.Column('suggested_action', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], name=op.f('fk_recommendations_batch_id_batches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recommendations'))
    )
    op.create_index(op.f('ix_recommendations_batch_id'), 'recommendations', ['batch_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_batch_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_process_steps_batch_id'), table_name='process_steps')
    op.drop_table('process_steps')
    op.drop_index(op.f('ix_inputs_cooperative_id'), table_name='inputs')
    op.drop_table('inputs')
    op.drop_index(op.f('ix_stocks_cooperative_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_fields_cooperative_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_batches_cooperative_id'), table_name='batches')
    op.drop_index(op.f('ix_batches_code'), table_name='batches')
    op.drop_table('batches')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_cooperative_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_cooperative_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_members_cooperative_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_cooperatives_name'), table_name='cooperatives')
    op.drop_table('cooperatives')
    # ### end Alembic commands ###
